# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.srcs/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/func1_bd_func1_1_0.xci
# IP: The module: 'func1_bd_func1_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.gen/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/func1_c_addsub_v12_0_i0/func1_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func1_c_addsub_v12_0_i0 || ORIG_REF_NAME==func1_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.gen/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/func1_c_addsub_v12_0_i1/func1_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func1_c_addsub_v12_0_i1 || ORIG_REF_NAME==func1_c_addsub_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.gen/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/constrs/func1.xdc
# XDC: The top module name and the constraint reference have the same name: 'func1_bd_func1_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.srcs/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/func1_bd_func1_1_0.xci
# IP: The module: 'func1_bd_func1_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.gen/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/func1_c_addsub_v12_0_i0/func1_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func1_c_addsub_v12_0_i0 || ORIG_REF_NAME==func1_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.gen/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/func1_c_addsub_v12_0_i1/func1_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func1_c_addsub_v12_0_i1 || ORIG_REF_NAME==func1_c_addsub_v12_0_i1} -quiet] -quiet

# XDC: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.gen/sources_1/bd/func1_bd/ip/func1_bd_func1_1_0/constrs/func1.xdc
# XDC: The top module name and the constraint reference have the same name: 'func1_bd_func1_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
