# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.srcs/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_bd_func2_1_0.xci
# IP: The module: 'func2_bd_func2_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_c_addsub_v12_0_i0/func2_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_c_addsub_v12_0_i0 || ORIG_REF_NAME==func2_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_c_addsub_v12_0_i1/func2_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_c_addsub_v12_0_i1 || ORIG_REF_NAME==func2_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_mult_gen_v12_0_i0/func2_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_mult_gen_v12_0_i0 || ORIG_REF_NAME==func2_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_mult_gen_v12_0_i1/func2_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_mult_gen_v12_0_i1 || ORIG_REF_NAME==func2_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_mult_gen_v12_0_i2/func2_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_mult_gen_v12_0_i2 || ORIG_REF_NAME==func2_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/constrs/func2.xdc
# XDC: The top module name and the constraint reference have the same name: 'func2_bd_func2_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.srcs/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_bd_func2_1_0.xci
# IP: The module: 'func2_bd_func2_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_c_addsub_v12_0_i0/func2_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_c_addsub_v12_0_i0 || ORIG_REF_NAME==func2_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_c_addsub_v12_0_i1/func2_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_c_addsub_v12_0_i1 || ORIG_REF_NAME==func2_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_mult_gen_v12_0_i0/func2_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_mult_gen_v12_0_i0 || ORIG_REF_NAME==func2_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_mult_gen_v12_0_i1/func2_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_mult_gen_v12_0_i1 || ORIG_REF_NAME==func2_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/func2_mult_gen_v12_0_i2/func2_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_mult_gen_v12_0_i2 || ORIG_REF_NAME==func2_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/ip/func2_bd_func2_1_0/constrs/func2.xdc
# XDC: The top module name and the constraint reference have the same name: 'func2_bd_func2_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
