# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/func1_clock.xdc

# XDC: imports/sysgen/func1.xdc

# Block Designs: bd/func1_bd/func1_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func1_bd || ORIG_REF_NAME==func1_bd} -quiet] -quiet

# IP: bd/func1_bd/ip/func1_bd_func1_1_0/func1_bd_func1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func1_bd_func1_1_0 || ORIG_REF_NAME==func1_bd_func1_1_0} -quiet] -quiet

# XDC: c:/Users/TARIK/Desktop/HDL_IP_Example_1/ip_catalog/func1.gen/sources_1/bd/func1_bd/func1_bd_ooc.xdc
