# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/xilinx_transfer_function_1_clock.xdc

# XDC: imports/sysgen/xilinx_transfer_function_1.xdc

# IP: ip/xilinx_transfer_function_1_c_addsub_v12_0_i0/xilinx_transfer_function_1_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_transfer_function_1_c_addsub_v12_0_i0 || ORIG_REF_NAME==xilinx_transfer_function_1_c_addsub_v12_0_i0} -quiet] -quiet

# IP: ip/xilinx_transfer_function_1_c_addsub_v12_0_i1/xilinx_transfer_function_1_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_transfer_function_1_c_addsub_v12_0_i1 || ORIG_REF_NAME==xilinx_transfer_function_1_c_addsub_v12_0_i1} -quiet] -quiet
