# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/func2_clock.xdc

# XDC: imports/sysgen/func2.xdc

# Block Designs: bd/func2_bd/func2_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_bd || ORIG_REF_NAME==func2_bd} -quiet] -quiet

# IP: bd/func2_bd/ip/func2_bd_func2_1_0/func2_bd_func2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==func2_bd_func2_1_0 || ORIG_REF_NAME==func2_bd_func2_1_0} -quiet] -quiet

# XDC: c:/Users/TARIK/Desktop/HDL/ip_catalog/func2.gen/sources_1/bd/func2_bd/func2_bd_ooc.xdc
